### ISSUE TITLE
https cert is only good for github urls

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodeschool/nodeschool.github.io#534]
<img width="670" alt="screen shot 2016-10-11 at 2 21 13 pm" src="https://cloud.githubusercontent.com/assets/498775/19282923/1a546dac-8fbe-11e6-97ec-326eaca5eac3.png">

**Comment by martinheidegger** [comment]
It is possible put a https proxy in front of github webhosting. or use a different webhost to host this url. In any case: Infra support welcome.

**Comment by jpwesselink** [comment]
A decent solution could be using Cloudflare, as decribed [here](https://developer.ubuntu.com/en/blog/2016/02/17/how-host-your-static-site-https-github-pages-and-cloudflare/). We probably need a different tier than their free one though because their free tier [does not support sha1 for older browsers](https://blog.cloudflare.com/sha-1-deprecation-no-browser-left-behind/).

I'd like to match the Google Analytics data from nodeschool.io against the statistics provided by Cloudflare to see how many of our visitors we would exclude if we would use Cloudflare's free tier.  

@martinheidegger Do you know who has access to this Google Analytics data?

Below Cloudflare stats.

Country | Percentage of Browsers Without SHA-2 Support
--- | ---
China | 6.08%
Cameroon | 5.39%
Yemen | 5.25%
Sudan | 4.69%
Egypt | 4.85%
Libya | 4.83%
Ivory Coast | 4.67%
Nepal | 4.52%
Ghana | 4.42%
Nigeria | 4.32%
Ethiopia | 3.82%
Iran | 3.78%
Tanzania | 3.72%
Syria | 3.63%
Paraguay | 3.53%
Angola | 3.50%
Kenya | 3.29%
Algeria | 3.12%
Bahrain | 3.09%
Nicaragua | 3.08%
Myanmar | 3.01%
Senegal | 2.94%
Bangladesh | 2.58%
Venezuela | 2.58%
Pakistan | 2.55%

**Comment by riyadhalnur** [comment]
My concern with using CloudFlare is that the connection between CloudFlare and GitHub will not be over SSL. Protecting 2/3 steps of the connection is the same as not having the protection at all.

**Comment by jpwesselink** [comment]
Doesn't it work like this?

https://nodeschool.io (at CloudFlare) < - > https://nodeschool.github.io (at GitHub)

**Comment by riyadhalnur** [comment]
More like this : 
*User <-- SSL --> CloudFlare <-- HTTP --> GitHub*

![Cloudflare](https://blog.cloudflare.com/content/images/2016/06/cloudflare_ssl_modes.png)

I don't think we can opt for Full SSL (Strict). Assuming we opt for Full SSL (2nd option), since CloudFlare doesn't validate the certificate, we would be risking a MITM attack.

**Comment by jpwesselink** [comment]
Aha. So Full SSL (Strict) would only suffice. What do we need for that?

**Comment by riyadhalnur** [comment]
From what I understand after reading this [thread](https://github.com/isaacs/github/issues/156), I don't think Full SSL (Strict) is going to work. Seems like for now, people are opting for Flexible SSL because Full SSL by itself doesn't really make much difference.

**Comment by martinheidegger** [comment]
A different thought: [now](https://zeit.co/now#pricing) costs 14.90/month for a custom_domain. And it would allow us to do some other, server-side processing as well. I wonder if we could get open-source sponsoring?

**Comment by jpwesselink** [comment]
@riyadhalnur I see, interesting thread. Ok, then CloudFlare is not going to work.

**Comment by martinheidegger** [comment]
(with now it is possible to serve ssl content)

**Comment by jpwesselink** [comment]
@rauchg, would it be possible for Zeit to sponsor us with hosting?

**Comment by riyadhalnur** [comment]
Yeah, would be great if we could get Zeit to sponsor our hosting. Would solve all our problems 👼

**Comment by SomeoneWeird** [comment]
> Protecting 2/3 steps of the connection is the same as not having the protection at all.

So you're suggesting we have 0 protection rather than _some_ ?

**Comment by SomeoneWeird** [comment]
If the origin server has SSL, cloudflare will 100% use that if you enable "Full SSL" (but not strict mode) when connecting back to origin. Just because something is not 100% perfect does not mean we can't use it.

**Comment by riyadhalnur** [comment]
@SomeoneWeird If there's a possibility of MITM attacks, yes I don't think it's worth protecting two-thirds of the path. The whole point of SSL is to mitigate MITM attacks among others.

**Comment by SomeoneWeird** [comment]
@riyadhalnur So you would rather leave everyone open to 100% possibility of MITM, rather than protecting against the 75% - albeit leaving the **hardest** 25% vulnerable? That seems very backwards.

**Comment by riyadhalnur** [comment]
If there was to be a MITM attack when you have 75% of it protected, then the loss of trust that will arise is more damaging. We'll essentially be giving people a false sense of security.

Another example would be this scenario - serving an app over HTTPS but storing user passwords in plain text in the database.

**Comment by SomeoneWeird** [comment]
So you would rather leave everything open to MITM to really basic adversaries (like somebody sitting on the same WiFi router as them) than protecting against the easiest 75% and now having to fend off nation-state level attackers that can MITM the infrastructure between Cloudflare and Github?

"Don't do nothing just because you can't do everything"

**Comment by riyadhalnur** [comment]
I get your point but you're assuming that only state level actors can inflict damage on the unprotected 25%. This [incident](http://thehackernews.com/2016/08/github-ssl-certificate.html) doesn't give me confidence.

**Comment by SomeoneWeird** [comment]
Even if we have 100% SSL across everything, it would still be a problem is a rogue CA handed out malicious certs. What we're talking about here doesn't (and can't!) protect against that.

**Comment by SomeoneWeird** [comment]
Enabling stuff like HPKP can be done _on top_ of us enabling SSL on the website, which would mitigate _some_ of the attack avenues of rogue-certificates. But we still need SSL.

**Comment by riyadhalnur** [comment]
That's a level of trust you walk in with when deploying SSL anywhere be it from Let's Encrypt, DigiCert, Comodo and so on. That like everything else goes to show nothing's 100% perfect but would you want to push that trust beyond that, as a real user?

**Comment by SomeoneWeird** [comment]
I know, that's what i'm arguing _for_. You're saying that just because we can't 100% trust everybody then we shouldn't use SSL?

**Comment by SomeoneWeird** [comment]
Anyway, enabling SSL (even if it's just for the 75%!) should be the first thing we do ASAP. We can reevaluate and keep arguing about it, but as long as we have _something_ soon, we have time to evaluate the best way to proceed from here.

**Comment by riyadhalnur** [comment]
I'm not saying we should never use SSL but personally, I would not want to push my trust beyond a certain point which is the case here.

We could definitely use CloudFlare for the time being and since we don't have any sensitive information passing through the servers (none comes to mind), it would theoretically be ok. I personally would still like an option like **now**.

**Comment by jpwesselink** [comment]
I agree with @SomeoneWeird that we should have something in place asap. I'm applying the CloudFlare setup to one of my domains to see how easy it is to implement. If it doesn't give me trouble we can implement it for nodeschool.io as well.

**Comment by gerrywastaken** [comment]
> @SomeoneWeird If there's a possibility of MITM attacks, yes I don't think it's worth protecting two-thirds of the path. The whole point of SSL is to mitigate MITM attacks among others.

@riyadhalnur I agree completely. Even with a secure connection, you're still only protecting part of the path, the hosting company can still access data. A browser/OS vendor could still supply fake root certificates and hijack all traffic. If we can't prevent against these things then we are just engaging in security theatre. The only reasonable step is to remove the hard drive from the server, store it in a vault and weld it shut.

Although, I have to admit the unlikely possibility that I might be wrong and that just maybe security isn't boolean and instead a balance between risk and convenience.

**Comment by riyadhalnur** [comment]
@gerrywastaken thank you for making my day a bit brighter 😄 
![cee2e2017554de6da437cb4c37dfb65be82a6da7949a56fc24e9ad41e00b84b7](https://cloud.githubusercontent.com/assets/3457571/19411667/ac15344e-9327-11e6-955a-b1cab144e56c.jpg)

**Comment by jpwesselink** [comment]
Current DNS records are like so: 

```bash
~ ➜ host -a nodeschool.io
Trying "nodeschool.io"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3241
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 10

;; QUESTION SECTION:
;nodeschool.io.                 IN      ANY

;; ANSWER SECTION:
nodeschool.io.          3334    IN      TXT     "v=spf1 include:mailgun.org ~all"
nodeschool.io.          3334    IN      NS      ns2.dnsimple.com.
nodeschool.io.          3334    IN      NS      ns3.dnsimple.com.
nodeschool.io.          3334    IN      NS      ns4.dnsimple.com.
nodeschool.io.          3334    IN      NS      ns1.dnsimple.com.
nodeschool.io.          3334    IN      SOA     ns1.dnsimple.com. admin.dnsimple.com. 1435660680 86400 7200 604800 300
nodeschool.io.          86400   IN      A       192.30.252.153
nodeschool.io.          3334    IN      MX      10 mxa.mailgun.org.
nodeschool.io.          3334    IN      MX      10 mxb.mailgun.org.
```

CloudFlare will copy 'em like this:

<img width="960" alt="screen shot 2016-10-19 at 12 21 21" src="https://cloud.githubusercontent.com/assets/1814479/19515200/bd47e8fc-95f6-11e6-8e6b-e5a5e8cb0a6f.png">




@brianloveswords if this looks sane to you, can change the nameservers like so?

Current Nameservers	| Change Nameservers to
------------------- | -------------------------
ns1.dnsimple.com		| brad.ns.cloudflare.com
ns2.dnsimple.com		| kristin.ns.cloudflare.com
ns3.dnsimple.com		| Remove this nameserver
ns4.dnsimple.com		| Remove this nameserver

**Comment by jpwesselink** [comment]
Thanks @brianloveswords. It seems that the changes have propagated properly and we have a valid certificate :tada: 

![screen shot 2016-10-21 at 00 28 44](https://cloud.githubusercontent.com/assets/1814479/19580265/7b22243a-9725-11e6-848c-193e5d4be1cf.png)

**Comment by brianloveswords** [comment]
@jpwesselink we good on this issue, think we can close it?

**Comment by jpwesselink** [comment]
With pleasure :)
